services:
  welcome-app:
    container_name: welcome-app
    image: testing/welcome
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    restart: unless-stopped
    user: "basic"