name: Deployment Pipeline

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
      operation:
        description: 'Select operation (build, deploy, both)'
        required: true
        type: choice
        options:
          - build-only
          - deploy-only
          - build-and-deploy

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
  
jobs:
  validate-version-format:
    name: Validate version format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate version format
        run: |
          if [[ ! "${{ github.event.inputs.release_version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format. Use semantic versioning (e.g., v1.0.0)"
            exit 1
          fi
  
  build-and-push-image:
    name: Build and Push
    needs: validate-version-format
    if: (inputs.operation == 'build-only')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.release_version }}

      - name: Create Git tag
        if: success()
        run: |
          TAG=${{ github.event.inputs.release_version }}
          
          # Check if tag exists locally or remotely
          if git rev-parse "$TAG" >/dev/null 2>&1 || \
             git ls-remote --tags origin "$TAG" | grep -q "$TAG"; then
            echo "::notice::Tag $TAG already exists. Skipping tag creation."
            exit 0
          fi

          # Create and push new tag
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag "$TAG"
          git push origin "$TAG"
          
  deploy:
    name: Deploy
    needs: validate-version-format
    if: ${{ github.event.inputs.operation == 'deploy-only' }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            #!/bin/bash
            set -euo pipefail
            
            # Pull latest image
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.release_version }}
            
            # Stop and remove old container
            docker stop welcome-app || true
            docker rm welcome-app || true
            
            # Run new container
            docker run -d \
              --name welcome-app \
              --restart unless-stopped \
              -p 8000:5000 \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.release_version }}
            
            # Cleanup old images
            docker image prune -af --filter "until=24h"
       
  build-and-deploy:
    name: Build, Push, & Deploy
    needs: validate-version-format
    if: ${{ github.event.inputs.operation == 'build-and-deploy' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.release_version }}

      - name: Create Git tag
        if: success()
        run: |
          TAG=${{ github.event.inputs.release_version }}
          
          # Check if tag exists locally or remotely
          if git rev-parse "$TAG" >/dev/null 2>&1 || \
             git ls-remote --exit-code origin "refs/tags/$TAG" >/dev/null 2>&1; then
            echo "::notice::Tag $TAG already exists. Skipping tag creation."
            exit 0
          fi

          # Create and push new tag
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag "$TAG"
          git push origin "$TAG"
          
      - name: SSH Deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            #!/bin/bash
            set -euo pipefail
            
            # Pull latest image
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.release_version }}
            
            # Stop and remove old container
            docker stop welcome-app || true
            docker rm welcome-app || true
            
            # Run new container
            docker run -d \
              --name welcome-app \
              --restart unless-stopped \
              -p 8000:5000 \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.release_version }}
            
            # Cleanup old images
            docker image prune -af --filter "until=24h"